import discord
from discord.ext import commands
import random

CODA_ID = 1029636983808598037
AUTHORIZED_USER_ID = 375801420739379222

ROASTS = [
    "Coda, you're like a software update. Whenever I see you, I think, 'Not now.'",
    "Coda, if you were a vegetable, you'd be a 'cabbage' because you're always in the way.",
    "Coda, you're like a cloud. When you disappear, it's a beautiful day.",
    "Coda, you're the reason God created the middle finger.",
    "Coda, if I wanted to hear from an idiot, I'd watch a reality show.",
    "Coda, you're like a software bug. Annoying and hard to get rid of.",
    "Coda, you're the human version of a participation trophy.",
    "Coda, if you were any more basic, you'd be a default font.",
    "Coda, you're like a broken pencil. Pointless.",
    "Coda, if you were a fruit, you'd be a 'cantaloupe' because you're always in the way.",
    "Coda, you're like a Wi-Fi signal. Weak and unreliable.",
    "Coda, if you were a spice, you'd be flour because you're bland and useless.",
    "Coda, you're like a software update. I don't want to deal with you right now.",
    "Coda, if you were a color, you'd be beige. Just plain boring.",
    "Coda, you're like a software bug. Annoying and hard to get rid of.",
    "Coda, if you were a fruit, you'd be a 'banana' because you're always slipping up.",
    "Coda, you're like a broken clock. Right twice a day, but still annoying.",
    "Coda, if you were a vegetable, you'd be a 'cabbage' because you're always in the way.",
    "Coda, you're like a cloud. When you disappear, it's a beautiful day.",
    "Coda, if you were a car, you'd be a 'lemon' because you're always breaking down.",
    "Coda, you're like a software update. I don't want to deal with you right now.",
    "Coda's brain runs on potato-powered WiFi.",
    "Coda tried to join Mensa but failed the CAPTCHA.",
    "Coda thinks 'Ctrl+Z' fixes real life.",
    "Coda's idea of deep thought is staring at a loading screen.",
    "Even autocorrect gives up on Coda.",
    "Coda once brought a spoon to a Zoom call.",
    "Coda claps when the microwave finishes.",
    "Coda googled how to turn off airplane mode... on a book.",
    "Coda thinks TikTok is the sound a clock makes.",
    "Coda’s reflection facepalms every morning.",
    "Coda wears sunglasses indoors to hide from responsibility.",
    "Coda's math skills are so bad, even his calculator quits.",
    "Coda thinks Java and coffee are the same thing.",
    "Coda’s spirit animal is a buffering icon.",
    "Coda tried to roast me and set his keyboard on fire.",
    "Coda once got lost in a Minecraft tutorial.",
    "Coda calls tech support for his toaster.",
    "Coda’s playlist is just elevator music and regret.",
    "Coda tried to be edgy and got a paper cut.",
    "Coda failed a lie detector for saying he’s smart.",
    "Coda’s YouTube recommendations are just ‘How to think.’",
    "Coda’s idea of cardio is dodging responsibility.",
    "Coda uses GPS to find his own point.",
    "Coda once got ratio’d in real life.",
    "Coda’s brain has less RAM than a Nokia.",
    "Coda brings a white flag to Uno.",
    "Coda tried to make a meme and became one.",
    "Coda’s aim in FPS games is more of a suggestion.",
    "Coda thinks IQ is a setting on his TV.",
    "Coda flosses... his brain cells away.",
    "Coda could lose a staring contest with a brick wall.",
    "Coda’s favorite genre is 'bad decisions.'",
    "Coda thinks WiFi password is ‘1234.’",
    "Coda’s the final boss of tutorial mode.",
    "Coda sleeps with the light on—so his ideas don’t feel alone.",
    "Coda spells ‘roast’ with a W.",
    "Coda tried to hack NASA and ended up on Club Penguin.",
    "Coda once blinked and forgot what he was doing.",
    "Coda’s brain takes coffee breaks without him.",
    "Coda’s spirit animal is a disconnected printer.",
    "Coda thinks ‘FPS’ means ‘Fries Per Second.’",
    "Coda's highlight reel is just bloopers.",
    "Coda has a sixth sense—it's confusion.",
    "Coda's thoughts come with patch notes.",
    "Coda once argued with Siri—and lost.",
    "Coda thought LOL stood for ‘Lots of Lettuce.’",
    "Coda skips tutorials, then rage quits real life.",
    "Coda's biggest achievement was turning off caps lock.",
    "Coda makes AI question intelligence.",
    "Coda once tripped over a wireless connection.",
    "Coda's KD ratio is so bad, NPCs feel bad for him.",
    "Coda once died in creative mode.",
    "Coda thinks 'camping' means pitching a real tent in Verdansk.",
    "Coda got sniped... in the tutorial.",
    "Coda's aim is so off, even the air gets nervous.",
    "Coda reloads in the middle of 1v1s like it's a ritual.",
    "Coda thinks 'lag' is a personality trait.",
    "Coda uses a shotgun like it's a sniper and still misses.",
    "Coda gets outplayed by the loading screen.",
    "Coda once threw a grenade at himself and blamed gravity.",
    "Coda thinks friendly fire means high-fiving his teammates... with bullets.",
    "Coda thinks ‘battle royale’ is a cooking show.",
    "Coda’s best strategy is hiding behind the AFK player.",
    "Coda once lost to a bot that was also lagging.",
    "Coda can’t even win in Solitaire.",
    "Coda’s game sense is still in beta.",
    "Coda rushes B and forgets the bomb.",
    "Coda builds in Fortnite like he's making abstract art.",
    "Coda’s signature move is falling off the map.",
    "Coda plays like he’s roleplaying a statue.",
    "Coda’s map awareness is the size of a minimap on 240p.",
    "Coda flashes himself... intentionally.",
    "Coda’s the reason ‘vote to kick’ exists.",
    "Coda’s kill streaks are just deaths in a row.",
    "Coda couldn’t clutch a 1v0.",
    "Coda's highest damage dealt was from fall damage.",
    "Coda thinks 'pushing mid' means sending an apology.",
    "Coda is the final boss... in reverse difficulty order.",
    "Coda gets carried so hard, his back is broken—by someone else.",
    "Coda once tried to wallbang and hit a vending machine IRL.",
    "Coda tries to quickscope with a melee weapon.",
    "Coda’s crosshair placement is a form of protest.",
    "Coda thinks ‘smurfing’ means dressing as Papa Smurf.",
    "Coda’s only win was from the enemy rage-quitting in pity.",
    "Coda hides so long, the game files forget he exists.",
    "Coda gets headshotted mid-emote—on accident.",
    "Coda’s go-to move is uninstalling.",
    "Coda thinks ‘meta’ is short for ‘meh, I’ll try something.’",
    "Coda reloads after one shot like it’s Call of Duty etiquette.",
    "Coda gets knifed in gunfights—twice.",
    "Coda’s idea of defense is hiding behind the scoreboard.",
    "Coda once flashbanged himself… in a racing game.",
    "Coda can’t find loot in a loot box.",
    "Coda gets banned in single-player.",
    "Coda thinks ‘clutch’ means his keyboard.",
    "Coda gets MVP: Most Valuable Problem.",
    "Coda mains defeat.",
    "Coda’s the only person who needs a tutorial for Pong.",
    "Coda’s controller disconnected—and no one noticed.",
    "Coda’s stream title is always ‘We Try Our Best.’",
    "Coda once got lost in his own house while holding a map.",
    "Coda thinks NFTs are short for 'Nice Funny Tweets.'",
    "Coda tried to use a toaster as a gaming console.",
    "Coda once rage quit a game of chess… with himself.",
    "Coda thought a thesaurus was a dinosaur.",
    "Coda plays hide and seek with common sense—and always wins by hiding it.",
    "Coda’s shadow left him for someone with better decision-making.",
    "Coda got benched in a single-player campaign.",
    "Coda thought ‘public speaking’ meant yelling in a Walmart.",
    "Coda's biggest achievement is charging his phone to 100%.",
    "Coda's thought process has more ads than YouTube.",
    "Coda once got scammed by a ‘click here to win nothing’ ad.",
    "Coda thinks a CPU is something you call when you're sick.",
    "Coda’s idea of multitasking is chewing gum and tripping at the same time.",
    "Coda once tried to fast-travel in real life.",
    "Coda asked Siri for a personality.",
    "Coda thought 'RAM' was a zodiac sign.",
    "Coda’s voice cracks more than Minecraft terrain generation.",
    "Coda accidentally super glued himself to his ego.",
    "Coda’s selfies are considered ‘crash reports’ by Instagram.",
    "Coda thinks sarcasm is a mineral.",
    "Coda’s alarm clock snoozes him.",
    "Coda once got hacked by a calculator.",
    "Coda’s sense of style is sponsored by ‘Don’t Do That.’",
    "Coda’s brain goes AFK during conversations.",
    "Coda once got friend-zoned by Clippy.",
    "Coda uses incognito mode to hide from commitment.",
    "Coda once blinked too hard and forgot his password.",
    "Coda talks like his mouth is on dial-up.",
    "Coda’s favorite hobby is making mistakes with confidence.",
    "Coda thought 'cloud storage' was for the weather.",
    "Coda gets motion sickness from scrolling TikTok.",
    "Coda once tried to copy-paste his homework... from a pizza menu.",
    "Coda’s inner voice uses subtitles.",
    "Coda once got roasted by a Magic 8-Ball.",
    "Coda thought VPN was a new boy band.",
    "Coda got catfished by an AI chatbot.",
    "Coda’s password is ‘password’—and still forgot it.",
    "Coda once took a BuzzFeed quiz and got ‘Error.’",
    "Coda still thinks ‘yeet’ is a vegetable.",
    "Coda says ‘GG’ after getting kicked from the lobby.",
    "Coda thought a resume was a video game character.",
    "Coda once emailed a screenshot to a printer.",
    "Coda’s brain lags in real life.",
    "Coda asked Alexa for dating advice. Alexa played sad music.",
    "Coda eats cereal with a fork and wonders why it’s dry.",
    "Coda got humbled by a captcha.",
    "Coda’s spirit animal is an unplugged USB.",
    "Coda once tried to update his brain’s firmware… with soup.",
    "Coda’s life is in beta and still full of bugs.",
    "Coda once tried to download RAM from a sketchy website—and it worked… in reverse.",
    "Coda thinks HDMI is a new type of sandwich.",
    "Coda got muted in a single-player game.",
    "Coda waves at NPCs hoping they'll wave back.",
    "Coda once got a virus from a Word document… on paper.",
    "Coda’s favorite genre is ‘buffering.’",
    "Coda clicks ‘Remind Me Tomorrow’ like it's a lifestyle choice.",
    "Coda plays Sudoku with a calculator.",
    "Coda’s playlist is just ‘low battery’ warnings on loop.",
    "Coda’s aura is 480p.",
    "Coda once asked tech support how to open a PDF physically.",
    "Coda got stuck in an automatic door.",
    "Coda uses light mode and still lives in darkness.",
    "Coda once used a ruler to measure time.",
    "Coda thought Ctrl+Alt+Delete was a secret code to the Matrix.",
    "Coda uses a Bluetooth speaker to talk to himself—wirelessly.",
    "Coda thought crop tops were for farming.",
    "Coda’s mind wanders… and never comes back.",
    "Coda asked for extra RAM at a restaurant.",
    "Coda logs into Zoom with a typewriter.",
    "Coda once said ‘bruh’ in Morse code—out loud.",
    "Coda updated his status and still couldn’t improve it.",
    "Coda tried to play chess and yelled ‘UNO!’",
    "Coda once downloaded a personality and got a 404.",
    "Coda’s brain is open-source, but no one contributes.",
    "Coda thought ‘AirDrop’ was a weather event.",
    "Coda got stuck in a revolving door and called it a side quest.",
    "Coda thought CAPTCHA was a Marvel villain.",
    "Coda thinks incognito mode makes him invisible IRL.",
    "Coda’s typing speed is 1 WPH—word per hour.",
    "Coda once watched a YouTube ad and thanked it for the content.",
    "Coda called tech support because his microwave ‘won’t connect to the internet.’",
    "Coda once misspelled his own name in voice chat.",
    "Coda treats error messages like horoscope readings.",
    "Coda once got disqualified from a walking simulator.",
    "Coda thought Bitcoin was a Minecraft item.",
    "Coda uses Comic Sans unironically—and proudly.",
    "Coda accidentally opened a command prompt and thought he hacked NASA.",
    "Coda’s phone auto-corrects ‘hello’ to ‘help.’",
    "Coda once tried to scroll on a printed photo.",
    "Coda wears Crocs in PowerPoint presentations.",
    "Coda’s search history is just ‘How do I Google?’",
    "Coda once got lost in IKEA and built a new identity.",
    "Coda’s personality was last updated in 2009.",
    "Coda thinks ‘cloud computing’ happens in thunderstorms.",
    "Coda thought Netflix buffering was the plot twist.",
    "Coda brings a fidget spinner to job interviews.",
    "Coda once tried to microwave a cold take.",
    "Coda’s IQ is measured in Minecraft ticks.",
    "Coda has a VPN just to hide from his own choices."
]

class Roast(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @discord.app_commands.command(name="roastcoda", description="Only the chosen one can roast Coda.")
    async def roast(self, interaction: discord.Interaction):
        if interaction.user.id != AUTHORIZED_USER_ID:
            await interaction.response.send_message("Only the chosen one can use this command.", ephemeral=True)
            return
        roast = random.choice(ROASTS)
        await interaction.response.send_message(f"<@{CODA_ID}> {roast}")

async def setup(bot):
    await bot.add_cog(Roast(bot))

